### PR TITLE
feat: run traefik job if is not already running

### PR DESCRIPTION
**Pull request by Sftobias**

### CODE REVIEW

**Comment by micafer** [comment]
@Sftobias Could may be better use "nomad job status" or something similar to check if the job is running?

**Comment by Sftobias** [comment]
> @Sftobias Could may be better use "nomad job status" or something similar to check if the job is running?

That command show jobs of different nodes, including other traefiks, so it wont work. However i can try to explore more in deep this approach.

**Comment by micafer** [comment]
We can merge this and then try to improve it later

**Review by micafer — APPROVED** [review]
LGTM

**Comment by Sftobias** [comment]
The traefik job is called `traefik-[dc-name]` so we can try to use as a filter

**Comment by Sftobias** [comment]
Another issue with the `nomad job status command`

ubuntu@dev-node-ifca-2:~$ sudo nomad job status
ID                         Type     Priority  Status          Submit Date
docuum                     system   75        running         2024-07-11T11:11:44Z
traefik-ifca-ai4eosc-dev   service  100       dead (stopped)  2024-07-11T11:21:38Z

If the job is dead it will not deploy it again (unless we run `nomad system gc` before, not a big deal)

**Comment by Sftobias** [comment]
Now the roles checks the nomad command, as suggested.

**Comment by micafer** [comment]
There is a problem in the tests:
```
  TASK [../../../../roles/nomad : Run service job] *******************************
  [WARNING]: conditional statements should not include jinja2 templating
  delimiters such as {{ }} or {% %}. Found: ("create_traefik_job is changed or
  traefik-{{ consul_dc_name }}' not in nomad_output.stdout")
  ASYNC OK on ai4os-ifca-wn-cpu-0: jid=j496128575513.15941
  changed: [ai4os-ifca-wn-cpu-0]
```

It says changed, so it has run the job command again. Could you check?

**Comment by micafer** [comment]
Error in verify fixed, it was a problem with the job name.

**Pull request merged**
